### ISSUE TITLE
Product section

### ISSUE THREAD

**Issue by werelax** [DanielDanielDanielDanielDaniel/nucleus#5]
* Implement the basic structure
* Alpha effects on scroll
* JSON generation

**Comment by werelax** [comment]
@DanielDanielDanielDanielDaniel In the mobile designs I see a modal window that I'm guessing open up when you click on an individual icon. Are we doing something similar to that for the desktop version?

**Comment by werelax** [comment]
Another question: in the design I see the text `5.3° / 6.2°` at the bottom of each icon box. I have no idea what that means 😅. What's that? And how can we generate it from the filename?

**Comment by DanielDanielDanielDanielDaniel** [comment]
@werelax 
to your question about the icon description inside the item:
- the icon items will be only the svg element, and nothing else

yes Modal desktop

- [ ] design modal desktop screen

**Comment by werelax** [comment]
About the icons: ok. I implemented something else but we can iterate over this when I upload the new version (tonight).

**Comment by werelax** [comment]
@DanielDanielDanielDanielDaniel I think we should close this issue and open new, more specific issues for each subsequent task
