### ISSUE TITLE
Responsive mode

### ISSUE THREAD

**Issue by werelax** [DanielDanielDanielDanielDaniel/nucleus#6]
Develop the mobile layout, as shown in the mobile designs.

**Comment by werelax** [comment]
@DanielDanielDanielDanielDaniel What about tables? The desktop version right now has a 1200px width wrapper. How do you think it should behave in wider/shorter screens? Should we make the wrapper fluid?

**Comment by DanielDanielDanielDanielDaniel** [comment]
@werelax yes fluid
also 4k widescreen looks like this:
![image](https://user-images.githubusercontent.com/8693416/37995105-a8afdc3c-3213-11e8-9264-689e49aeead1.png)
which is not a good design.

- [ ] design widescreen responsive behavior

**Comment by DanielDanielDanielDanielDaniel** [comment]
i need to test in sketch what works well,
also sorry for my incomplete designs. I could have done 10x better ;)

**Comment by werelax** [comment]
@DanielDanielDanielDanielDaniel do not worry! The designs are fine. I think it may be faster to experiment directly with the code. I've already implemented what I think is a reasonable behavior for tablet and maybe we could use something similar for widescreens. I'll upload a new version tonight.

**Comment by werelax** [comment]
@DanielDanielDanielDanielDaniel I think we should close this issue once the PR is merged and then open new, more specific ones for each derived task.
